name: django-ocr-service
channels:
  - conda-forge
  - defaults
dependencies:
  - django=3.2
  - kafka-python=2.0.2
  - pip=21.1
  - psycopg2=2.8
  - python=3.9
  - djangorestframework
  - pytesseract
  - pypdf2
  - pdf2image
  - boto3
  - pre_commit
  - pyyaml
  - black
  - opencv
  - pytest-cov
  - pytest-django
  - uvicorn
  - gunicorn
  - pandas
  - requests
  - pymongo
  - dnspython
  - pip:
      - django-expiring-token
      - django-storages
      - s3urls
      - aioboto3
      - django-q