name: django-ocr-service
channels:
  - conda-forge
  - defaults
dependencies:
  - django=3.2
  - pip=21.1
  - psycopg2=2.8
  - python=3.9
  - djangorestframework==3.12.4
  - pytesseract=0.3.8
  - pypdf2=1.26.0
  - pdf2image=1.15.1
  - boto3=1.17.49
  - pre_commit
  - pyyaml
  - black
  - opencv=4.5.2
  - pytest-cov
  - pytest-django
  - uvicorn
  - gunicorn
  - pandas=1.2.5
  - requests
  - pymongo=3.11.4
  - dnspython=1.16
  - pip:
      - django-expiring-token==1.0.2
      - django-storages==1.11.1
      - s3urls
      - aioboto3==9.0.0
      - django-q==1.3.9
      - checksum