# Generated by Django 3.2.4 on 2021-06-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial_ocr_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrinput',
            name='ocr_text',
        ),
        migrations.AddField(
            model_name='ocrinput',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
