# Generated by Django 3.2.4 on 2021-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_ocr_initial_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrinput",
            name="result_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ocrinput",
            name="ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
