# Generated by Django 3.2.4 on 2021-06-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinput',
            name='checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocroutput',
            name='checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
